[@feathersjs/authentication-oauth2] Fix TypeScript version
Error: feathersjs__authentication-oauth2 depends on passport-github but
has a lower required TypeScript version.